GET http://localhost:3000/abstracts

###
GET http://localhost:3000/abstracts/646c6809c69f48a4497260f4

###
POST http://localhost:3000/abstracts/
Content-Type: application/json

{
  "url": "dldfoewi231231",
  "advancedAbstract": "this is advanced",
  "originalAbstract": "this is orignal abst",
  "elementaryAbstract": "this is also required"
}
###
DELETE http://localhost:3000/abstracts/

###
POST http://localhost:3000/users/login/
Content-Type: application/json

{
  "username":"Nazanin"
}

